#! /bin/sh

sxhkd &
sh ~/.fehbg &
sh ~/.config/bar/bar.sh | lemonbar -f Inconsolata -f "Noto Sans" -g 1500x32+10+10 &
compton -b &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config -m top_padding 42
bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
